### ISSUE TITLE
development copy not working on site

### ISSUE THREAD

**Issue by nasihere** [nasihere/shared#1]
HI Uttam,

Bundle file reporting there's lots of same controller name been used in billing. It confused site. please check dist/folder output file n try to run your page.

also router navigator logic isn't been implemented. please make router logic one page app.

thanks
nasir

**Comment by nasihere** [comment]
Please find the issue ..

<img width="1621" alt="screen shot 2015-11-08 at 11 40 45 am" src="https://cloud.githubusercontent.com/assets/4184377/11022200/95c4789e-860d-11e5-92c1-1e37719b26c8.png">

**Comment by uttamsolanki** [comment]
Sorry sir I m at home so here net problem ..I will check n fix all bug on
Sunday....plz give me time...
